name: Upload to S3 on Push

on:
  push:
    branches:
      - master  # Specify the branch here
env:
  BUCKET_NAME: "tftests3"
  AWS_REGION: "us-east-1"
  GITHUB_REF: "master"
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::064195113262:role/github-actions-role
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}

    - name: Sync repository to S3
      run: |
        aws s3 sync . s3://${{ env.BUCKET_NAME }} --exclude "node_modules/**" --exclude ".git/**" --exclude "dist/**" --exclude ".github/**" --exclude "README.md"
      env:
        AWS_REGION: ${{ env.AWS_REGION }}


 
