name: Upload to S3 on Push

on:
  push:
    branches:
      - master  # Specify the branch here
env:
  BUCKET_NAME : "standil1"
  AWS_REGION : "il-central-1"
  
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::064195113262:role/github-actions-role
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Extract commit hash
      shell: bash
      run: echo "##[set-output name=commit_hash;]$(echo "$GITHUB_SHA")"
      id: extract_hash 

    - name:  Copy build to S3
      run: |
          zip -r ./artifacts/project.zip . -x node_modules/**\* .git/**\* dist/**\* dist/**\*          
          aws s3 sync  ${GITHUB_WORKSPACE}/artifacts s3://${{ env.BUCKET_NAME }}/${{ steps.extract_branch.outputs.branch }}/latest
